name: 'Verify Pull Request Labels'
author: 'step-security'
description: 'Verify that the PR has a valid label'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  valid-labels:
    description: 'List of valid labels'
    required: true
  invalid-labels:
    description: 'List of invalid labels'
    required: false
    default: ''
  pull-request-number:
    description: 'The Pull Request number'
    required: false
  disable-reviews:
    description: 'Should the action post reviews on PRs'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/verify-pr-label-action:v1.4.0@sha256:01e50264b72f4ff5ca26de3034ee02e0930cf0645531ec5c97d0010f105ebe93' # v1.4.0
  args:
    - ${{ inputs.valid-labels }}
    - ${{ inputs.invalid-labels }}
    - ${{ inputs.pull-request-number }}
    - ${{ inputs.disable-reviews }}
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
